direction: right

expectations: {
    ds1: spike\nduration
    ds1.shape: circle
    ds2: spike\namplitude
    ds2.shape: circle
    ds3: normal\nreplicas\ncount
    ds3.shape: circle

    near: bottom-left
    shape: oval
}

expectations -> deployment: shape

deployment: max\nreplicas count
deployment: {
    near: top-center
    shape: circle
}

deployment -> metric: exposes

metric: actual\nreplicas count
metric: {
    near: bottom-right
    shape: circle
}

metric -> expectations: confirms
