direction: right

model: model\n(expectations)
model: {
  shape: circle
  near: bottom-left
  width: 150
  height: 150
}

deployment: {
  shape: circle
  near: top-center
  width: 150
  height: 150
}

model -> deployment: shapes {
  style: {
    stroke-width: 5
  }
}
