direction: right

model: {
  shape: circle
  near: bottom-left
  width: 150
  height: 150
}

deployment: {
  shape: circle
  near: top-center
  width: 150
  height: 150
}
monitoring: {
  shape: circle
  near: bottom-right
  width: 150
  height: 150
}

model -> deployment: shapes {
  style: {
    stroke-width: 5
  }
}
deployment -> monitoring: exposes\nmodel-related metrics
monitoring -> model: refines {
  style: {
    stroke-width: 5
  }
}
